quarkus:
  datasource:
    db-kind: mysql
    reactive:
      url: vertx-reactive:mysql://localhost:3306/remember-core2-dev?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: kokokoko123
  hibernate-orm:
    sql-load-script: import.sql
    database:
      generation: drop-and-create
    log:
      sql: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
